import type { PermissionScope } from './enums';
import { PERMISSIONS, type Permission } from './permissions';

const P = PERMISSIONS;

export interface RoleDefinition {
  key: string;
  name: string;
  description: string;
  /** Lower is more senior. Drives the escalation ladder. */
  level: number;
  /** `'*'` grants every registered permission at ALL scope. */
  permissions: '*' | { permission: Permission; scope?: PermissionScope }[];
}

const all = (...permissions: Permission[]) =>
  permissions.map((permission) => ({ permission, scope: 'ALL' as PermissionScope }));

const team = (...permissions: Permission[]) =>
  permissions.map((permission) => ({ permission, scope: 'TEAM' as PermissionScope }));

const own = (...permissions: Permission[]) =>
  permissions.map((permission) => ({ permission, scope: 'OWN' as PermissionScope }));

/**
 * The system role matrix, mirroring docs/07-rbac-permissions.md §3.
 *
 * These roles are created with `isSystem: true` and cannot be edited or
 * deleted — an organisation clones them to build custom roles instead. That
 * removes any path to accidentally locking every administrator out.
 *
 * Lives in @ayv/types (rather than apps/api) so both the NestJS API and the
 * Next.js app's own admin/bootstrap routes can provision the same roles
 * without duplicating this matrix.
 */
export const SYSTEM_ROLES: RoleDefinition[] = [
  {
    key: 'SUPER_ADMIN',
    name: 'Super Admin',
    description: 'Unrestricted access to every module and setting.',
    level: 0,
    permissions: '*',
  },

  {
    key: 'CEO',
    name: 'CEO',
    description: 'Full visibility across the company with executive controls.',
    level: 10,
    permissions: [
      ...all(
        P.ORG_READ,
        P.SETTING_READ,
        P.USER_READ,
        P.ROLE_READ,
        P.TEAM_READ,
        P.AUDIT_READ,
        P.LEAD_READ,
        P.LEAD_UPDATE,
        P.LEAD_ASSIGN,
        P.LEAD_EXPORT,
        P.PIPELINE_READ,
        P.QUOTATION_READ,
        P.QUOTATION_APPROVE,
        P.PROPOSAL_READ,
        P.PROPOSAL_APPROVE,
        P.CONTRACT_READ,
        P.CONTRACT_APPROVE,
        P.ACTIVITY_READ,
        P.CLIENT_READ,
        P.CLIENT_UPDATE,
        P.CLIENT_HEALTH_READ,
        P.TICKET_READ,
        P.PROJECT_READ,
        P.PROJECT_UPDATE,
        P.TASK_READ,
        P.TIMELOG_READ,
        P.CREATIVE_READ,
        P.APPROVAL_READ,
        P.APPROVAL_DECIDE,
        P.EMPLOYEE_READ,
        P.ATTENDANCE_READ,
        P.LEAVE_READ,
        P.PAYROLL_READ,
        P.PERFORMANCE_READ,
        P.CANDIDATE_READ,
        P.INVOICE_READ,
        P.INVOICE_APPROVE,
        P.PAYMENT_READ,
        P.EXPENSE_READ,
        P.EXPENSE_APPROVE,
        P.PNL_READ,
        P.BUDGET_MANAGE,
        P.SOP_READ,
        P.SOP_MANAGE,
        P.AUTOMATION_READ,
        P.AUTOMATION_MANAGE,
        P.ASSET_READ,
        P.KNOWLEDGE_READ,
        P.KNOWLEDGE_MANAGE,
        P.POST_READ,
        P.CAMPAIGN_READ,
        P.AI_USE,
        P.AI_CONFIGURE,
        P.AI_APPROVE,
        P.DASHBOARD_READ,
        P.DASHBOARD_EXECUTIVE,
        P.REPORT_READ,
        P.REPORT_EXPORT,
      ),
    ],
  },

  {
    key: 'OPERATIONS_HEAD',
    name: 'Operations Head',
    description: 'Runs delivery across every project and department.',
    level: 20,
    permissions: [
      ...all(
        P.USER_READ,
        P.TEAM_READ,
        P.TEAM_MANAGE,
        P.CLIENT_READ,
        P.CLIENT_UPDATE,
        P.CLIENT_HEALTH_READ,
        P.TICKET_READ,
        P.TICKET_MANAGE,
        P.PROJECT_READ,
        P.PROJECT_CREATE,
        P.PROJECT_UPDATE,
        P.PROJECT_DELETE,
        P.TASK_READ,
        P.TASK_CREATE,
        P.TASK_UPDATE,
        P.TASK_DELETE,
        P.TASK_ASSIGN,
        P.TIMELOG_READ,
        P.CREATIVE_READ,
        P.CREATIVE_CREATE,
        P.CREATIVE_UPDATE,
        P.APPROVAL_READ,
        P.APPROVAL_DECIDE,
        P.ASSET_READ,
        P.ASSET_CREATE,
        P.SOP_READ,
        P.SOP_MANAGE,
        P.AUTOMATION_READ,
        P.AUTOMATION_MANAGE,
        P.KNOWLEDGE_READ,
        P.POST_READ,
        P.POST_MANAGE,
        P.CAMPAIGN_READ,
        P.CAMPAIGN_MANAGE,
        P.AI_USE,
        P.DASHBOARD_READ,
        P.REPORT_READ,
      ),
      ...team(P.AUDIT_READ, P.ATTENDANCE_READ, P.LEAVE_READ, P.LEAVE_APPROVE, P.EXPENSE_READ),
      ...all(P.LEAD_READ, P.PROJECT_READ, P.EMPLOYEE_READ, P.INVOICE_READ),
    ],
  },

  {
    key: 'SALES_HEAD',
    name: 'Sales Head',
    description: 'Owns the pipeline, targets and the sales team.',
    level: 25,
    permissions: [
      ...all(
        P.LEAD_READ,
        P.LEAD_CREATE,
        P.LEAD_UPDATE,
        P.LEAD_DELETE,
        P.LEAD_ASSIGN,
        P.LEAD_CONVERT,
        P.LEAD_EXPORT,
        P.PIPELINE_READ,
        P.PIPELINE_MANAGE,
        P.QUOTATION_READ,
        P.QUOTATION_CREATE,
        P.QUOTATION_UPDATE,
        P.QUOTATION_APPROVE,
        P.PROPOSAL_READ,
        P.PROPOSAL_CREATE,
        P.PROPOSAL_APPROVE,
        P.CONTRACT_READ,
        P.CONTRACT_CREATE,
        P.ACTIVITY_READ,
        P.ACTIVITY_CREATE,
        P.CLIENT_READ,
        P.CLIENT_CREATE,
        P.CLIENT_UPDATE,
        P.CAMPAIGN_READ,
        P.CAMPAIGN_MANAGE,
        P.AI_USE,
      ),
      ...team(
        P.USER_READ,
        P.AUDIT_READ,
        P.CLIENT_HEALTH_READ,
        P.PROJECT_READ,
        P.TASK_READ,
        P.TIMELOG_READ,
        P.ATTENDANCE_READ,
        P.LEAVE_READ,
        P.LEAVE_APPROVE,
        P.INVOICE_READ,
        P.EXPENSE_READ,
        P.TICKET_READ,
        P.AUTOMATION_READ,
        P.AUTOMATION_MANAGE,
        P.DASHBOARD_READ,
      ),
      ...all(P.REPORT_READ),
    ],
  },

  {
    key: 'SALES_EXECUTIVE',
    name: 'Sales Executive',
    description: 'Works their own pipeline end to end.',
    level: 50,
    permissions: [
      ...own(
        P.LEAD_READ,
        P.LEAD_UPDATE,
        P.LEAD_CONVERT,
        P.QUOTATION_READ,
        P.QUOTATION_CREATE,
        P.QUOTATION_UPDATE,
        P.PROPOSAL_READ,
        P.PROPOSAL_CREATE,
        P.CONTRACT_READ,
        P.ACTIVITY_READ,
        P.INVOICE_READ,
        P.EXPENSE_READ,
        P.EXPENSE_CREATE,
        P.ATTENDANCE_READ,
        P.LEAVE_READ,
        P.LEAVE_CREATE,
        P.PERFORMANCE_READ,
        P.TASK_READ,
        P.TASK_UPDATE,
        P.TIMELOG_READ,
        P.TIMELOG_CREATE,
        P.TICKET_READ,
        P.CAMPAIGN_READ,
        P.AI_USE,
        P.DASHBOARD_READ,
      ),
      ...all(P.LEAD_CREATE, P.ACTIVITY_CREATE, P.PIPELINE_READ, P.SOP_READ, P.KNOWLEDGE_READ),
      ...team(P.CLIENT_READ, P.PROJECT_READ),
    ],
  },

  {
    key: 'CREATIVE_HEAD',
    name: 'Creative Head',
    description: 'Owns creative quality, the production queue and approvals.',
    level: 25,
    permissions: [
      ...all(
        P.CREATIVE_READ,
        P.CREATIVE_CREATE,
        P.CREATIVE_UPDATE,
        P.APPROVAL_READ,
        P.APPROVAL_DECIDE,
        P.ASSET_READ,
        P.ASSET_CREATE,
        P.ASSET_DELETE,
        P.POST_READ,
        P.POST_MANAGE,
        P.POST_PUBLISH,
        P.KNOWLEDGE_READ,
        P.SOP_READ,
        P.AI_USE,
      ),
      ...team(
        P.USER_READ,
        P.CLIENT_READ,
        P.CLIENT_HEALTH_READ,
        P.PROJECT_READ,
        P.PROJECT_UPDATE,
        P.TASK_READ,
        P.TASK_CREATE,
        P.TASK_UPDATE,
        P.TASK_ASSIGN,
        P.TIMELOG_READ,
        P.ATTENDANCE_READ,
        P.LEAVE_READ,
        P.LEAVE_APPROVE,
        P.PERFORMANCE_READ,
        P.EXPENSE_READ,
        P.SOP_MANAGE,
        P.AUTOMATION_READ,
        P.AUTOMATION_MANAGE,
        P.DASHBOARD_READ,
      ),
      ...all(P.CAMPAIGN_READ, P.LEAD_READ),
    ],
  },

  {
    key: 'DESIGNER',
    name: 'Designer',
    description: 'Executes design work from the creative queue.',
    level: 60,
    permissions: [
      ...own(
        P.CREATIVE_READ,
        P.CREATIVE_UPDATE,
        P.TASK_READ,
        P.TASK_UPDATE,
        P.TIMELOG_READ,
        P.TIMELOG_CREATE,
        P.PROJECT_READ,
        P.ATTENDANCE_READ,
        P.LEAVE_READ,
        P.LEAVE_CREATE,
        P.PERFORMANCE_READ,
        P.EXPENSE_READ,
        P.EXPENSE_CREATE,
        P.AI_USE,
        P.DASHBOARD_READ,
      ),
      ...all(P.ASSET_READ, P.ASSET_CREATE, P.KNOWLEDGE_READ, P.SOP_READ, P.CLIENT_READ),
    ],
  },

  {
    key: 'VIDEO_EDITOR',
    name: 'Video Editor',
    description: 'Executes video production from the creative queue.',
    level: 60,
    permissions: [
      ...own(
        P.CREATIVE_READ,
        P.CREATIVE_UPDATE,
        P.TASK_READ,
        P.TASK_UPDATE,
        P.TIMELOG_READ,
        P.TIMELOG_CREATE,
        P.PROJECT_READ,
        P.ATTENDANCE_READ,
        P.LEAVE_READ,
        P.LEAVE_CREATE,
        P.PERFORMANCE_READ,
        P.EXPENSE_READ,
        P.EXPENSE_CREATE,
        P.AI_USE,
        P.DASHBOARD_READ,
      ),
      ...all(P.ASSET_READ, P.ASSET_CREATE, P.KNOWLEDGE_READ, P.SOP_READ, P.CLIENT_READ),
    ],
  },

  {
    key: 'DEVELOPER',
    name: 'Developer',
    description: 'Builds and maintains websites and technical deliverables.',
    level: 60,
    permissions: [
      ...own(
        P.TASK_READ,
        P.TASK_UPDATE,
        P.TIMELOG_READ,
        P.TIMELOG_CREATE,
        P.PROJECT_READ,
        P.ATTENDANCE_READ,
        P.LEAVE_READ,
        P.LEAVE_CREATE,
        P.PERFORMANCE_READ,
        P.EXPENSE_READ,
        P.EXPENSE_CREATE,
        P.AI_USE,
        P.DASHBOARD_READ,
      ),
      ...all(P.ASSET_READ, P.KNOWLEDGE_READ, P.SOP_READ, P.CLIENT_READ),
    ],
  },

  {
    key: 'HR',
    name: 'Human Resources',
    description: 'Owns people operations end to end.',
    level: 30,
    permissions: [
      ...all(
        P.USER_READ,
        P.USER_CREATE,
        P.USER_UPDATE,
        P.USER_DELETE,
        P.TEAM_READ,
        P.TEAM_MANAGE,
        P.EMPLOYEE_READ,
        P.EMPLOYEE_MANAGE,
        P.ATTENDANCE_READ,
        P.ATTENDANCE_MANAGE,
        P.LEAVE_READ,
        P.LEAVE_APPROVE,
        P.PAYROLL_READ,
        P.PAYROLL_MANAGE,
        P.PERFORMANCE_READ,
        P.PERFORMANCE_MANAGE,
        P.CANDIDATE_READ,
        P.CANDIDATE_MANAGE,
        P.SOP_READ,
        P.SOP_MANAGE,
        P.KNOWLEDGE_READ,
        P.KNOWLEDGE_MANAGE,
        P.AI_USE,
        P.REPORT_READ,
      ),
      ...own(P.LEAVE_CREATE, P.EXPENSE_READ, P.EXPENSE_CREATE),
      ...team(P.DASHBOARD_READ),
    ],
  },

  {
    key: 'FINANCE',
    name: 'Finance',
    description: 'Owns billing, expenses, payroll execution and reporting.',
    level: 30,
    permissions: [
      ...all(
        P.INVOICE_READ,
        P.INVOICE_CREATE,
        P.INVOICE_UPDATE,
        P.INVOICE_APPROVE,
        P.PAYMENT_READ,
        P.PAYMENT_MANAGE,
        P.EXPENSE_READ,
        P.EXPENSE_CREATE,
        P.EXPENSE_APPROVE,
        P.VENDOR_MANAGE,
        P.PNL_READ,
        P.BUDGET_MANAGE,
        P.PAYROLL_READ,
        P.PAYROLL_MANAGE,
        P.CLIENT_READ,
        P.PROJECT_READ,
        P.USER_READ,
        P.EMPLOYEE_READ,
        P.AUDIT_READ,
        P.CONTRACT_READ,
        P.QUOTATION_READ,
        P.LEAD_READ,
        P.KNOWLEDGE_READ,
        P.SOP_READ,
        P.AI_USE,
        P.DASHBOARD_READ,
        P.REPORT_READ,
        P.REPORT_EXPORT,
      ),
    ],
  },

  {
    key: 'INTERN',
    name: 'Intern',
    description: 'Limited access to assigned work only.',
    level: 90,
    permissions: [
      ...own(
        P.TASK_READ,
        P.TASK_UPDATE,
        P.TIMELOG_READ,
        P.TIMELOG_CREATE,
        P.PROJECT_READ,
        P.CREATIVE_READ,
        P.ATTENDANCE_READ,
        P.LEAVE_READ,
        P.LEAVE_CREATE,
        P.EXPENSE_READ,
        P.EXPENSE_CREATE,
        P.AI_USE,
        P.DASHBOARD_READ,
      ),
      ...all(P.KNOWLEDGE_READ, P.SOP_READ, P.ASSET_READ),
    ],
  },

  {
    key: 'CLIENT',
    name: 'Client',
    description:
      'Portal access, hard-scoped to the client account. Never sees internal costs, ' +
      'margins, team data or other clients.',
    level: 100,
    permissions: [
      ...own(
        P.PROJECT_READ,
        P.TASK_READ,
        P.INVOICE_READ,
        P.PAYMENT_READ,
        P.APPROVAL_READ,
        P.APPROVAL_DECIDE,
        P.ASSET_READ,
        P.TICKET_READ,
        P.TICKET_MANAGE,
        P.CLIENT_READ,
        P.CAMPAIGN_READ,
        P.POST_READ,
        P.DASHBOARD_READ,
        P.REPORT_READ,
      ),
    ],
  },
];

/** Human-readable descriptions for the permission registry and role editor. */
export const PERMISSION_DESCRIPTIONS: Record<string, string> = {
  [P.ORG_READ]: 'View organisation profile',
  [P.ORG_UPDATE]: 'Edit organisation profile',
  [P.USER_READ]: 'View users',
  [P.USER_CREATE]: 'Invite and create users',
  [P.USER_DELETE]: 'Deactivate users',
  [P.ROLE_ASSIGN]: 'Change a user’s role',
  [P.AUDIT_READ]: 'View the audit trail',
  [P.LEAD_READ]: 'View leads',
  [P.LEAD_CONVERT]: 'Convert a won lead into a client',
  [P.PAYROLL_READ]: 'View payroll and salary data',
  [P.PNL_READ]: 'View profit and loss',
  [P.DASHBOARD_EXECUTIVE]: 'View the executive dashboard',
  [P.AI_CONFIGURE]: 'Configure AI agents and their autonomy',
};
